# Nightly SQM Measurements
**GOAL:**
<br> Plot nightly SQM measurements:
- *x-axis* = Time [sunset -> sunrise]
- *y-axis* = SQM 'mags'
- Filtere the data by cloudcover, lunar phase.

## 1) Read the data

In [207]:
import sqm_plot202X
import numpy as np
import datetime
import pandas as pd
import sys
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.cm as cm
import plotly.express as px
import plotly.graph_objects as go

In [208]:
# User inputs:
loc = 'SPZN' # Available data: FCZN, DSZN, HILT, SPZN
year = '2020'
month = '7'

In [209]:
# Load the CSV
fdir = '/Users/jacksontobin/Local_Documents/NightTime_Research/FoCo Night Sky Team/SQM_DATA/SQM_COMPLETE'
df_csv = f'{fdir}/{loc}_combined.csv'
df = pd.read_csv(df_csv)
df = df.set_index(df['date'])
df.index = pd.to_datetime(df.index)

# Remove bogus data
cond = (df['mags'] < 0)
df['mags'] = df['mags'].mask(cond, np.nan)

# Filter the date by years
df_yr = df[(df.index < datetime.datetime(year=int(year)+1, month=1, day=1)) & 
           (df.index > datetime.datetime(year=int(year),   month=1, day=1))]

# Filter out data if the solar elevation is > -18 (astronomical twighlight cutoff)
df_yr.loc[(df_yr['sunalt_deg']) >= -18, 'mags'] = float('nan')

In [210]:
# Choose the dates
df_mo = df_yr[df_yr.index.month.isin([int(month)])]

## 3) Sort data by day?

### Filter by Lunar and Cloud data

NOTE: 'date' column is a datetime object in the local time!

In [ ]:
# Convert the index to DateTime objects
df_mo.index = pd.to_datetime(df_mo.index)

# Convert to MST
# df_mo.index = df_mo.index.tz_localize('UTC').tz_convert('America/Denver')

,Unnamed: 0.1,date,mags,sunalt_deg,lunar_alt,lunar_az,lunar_fraction,lunar_phase,lunarphaseclass,Unnamed: 0,cloudcover,cloudcover_low,cloudcover_mid,cloudcover_high,CC
date,,,,,,,,,,,,,,,
2020-07-01 00:00:00,105549,2020-07-01 00:00:00,20.08,-24.228969,65.322160,204.544262,0.790016,0.365214,Gibbous,48.0,41.0,0.0,26.0,41.0,SCT
2020-07-01 00:01:00,105550,2020-07-01 00:01:00,20.05,-24.281309,65.556866,204.299168,0.790081,0.365214,Gibbous,48.0,41.0,0.0,26.0,41.0,SCT
2020-07-01 00:02:00,105551,2020-07-01 00:02:00,20.07,-24.332871,65.791449,204.054073,0.790147,0.365214,Gibbous,48.0,41.0,0.0,26.0,41.0,SCT
2020-07-01 00:03:00,105552,2020-07-01 00:03:00,20.06,-24.383652,66.025922,203.808965,0.790212,0.365214,Gibbous,48.0,41.0,0.0,26.0,41.0,SCT
2020-07-01 00:04:00,105553,2020-07-01 00:04:00,20.10,-24.433650,66.260266,203.563843,0.790278,0.365214,Gibbous,48.0,41.0,0.0,26.0,41.0,SCT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-07-31 23:55:00,122227,2020-07-31 23:55:00,19.31,-28.826771,40.131685,229.317891,0.922016,0.426347,Gibbous,792.0,37.0,0.0,37.0,24.0,SCT
2020-07-31 23:56:00,122228,2020-07-31 23:56:00,19.32,-28.889598,40.349421,229.074545,0.922056,0.426347,Gibbous,792.0,37.0,0.0,37.0,24.0,SCT
2020-07-31 23:57:00,122229,2020-07-31 23:57:00,19.32,-28.951610,40.567065,228.831172,0.922096,0.426347,Gibbous,792.0,37.0,0.0,37.0,24.0,SCT
2020-07-31 23:58:00,122230,2020-07-31 23:58:00,19.33,-29.012802,40.784617,228.587785,0.922136,0.426347,Gibbous,792.0,37.0,0.0,37.0,24.0,SCT
2020-07-31 23:59:00,122231,2020-07-31 23:59:00,19.33,-29.073173,41.002073,228.344384,0.922176,0.426347,Gibbous,792.0,37.0,0.0,37.0,24.0,SCT

In [212]:

# Create a new column: all 8pm-6am periods fall on the same date
df_mo['night'] = (df_mo.index - pd.Timedelta(hours=6)).normalize().tz_localize(None) # strips TZ for clean grouping
# df_mo['night'] = np.where(df_mo.index.hour >= 12, df_mo.index.date, (df_mo.index - pd.Timedelta(days=1)).date)  # Adjust for times after midnight
df_mo

/var/folders/hx/hcs55bp10f5fdvcmjf0rmf4r0000gn/T/ipykernel_70673/2111197200.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Unnamed: 0.1,date,mags,sunalt_deg,lunar_alt,lunar_az,lunar_fraction,lunar_phase,lunarphaseclass,Unnamed: 0,cloudcover,cloudcover_low,cloudcover_mid,cloudcover_high,CC,night
date,,,,,,,,,,,,,,,,
2020-07-01 00:00:00,105549,2020-07-01 00:00:00,20.08,-24.228969,65.322160,204.544262,0.790016,0.365214,Gibbous,48.0,41.0,0.0,26.0,41.0,SCT,2020-06-30
2020-07-01 00:01:00,105550,2020-07-01 00:01:00,20.05,-24.281309,65.556866,204.299168,0.790081,0.365214,Gibbous,48.0,41.0,0.0,26.0,41.0,SCT,2020-06-30
2020-07-01 00:02:00,105551,2020-07-01 00:02:00,20.07,-24.332871,65.791449,204.054073,0.790147,0.365214,Gibbous,48.0,41.0,0.0,26.0,41.0,SCT,2020-06-30
2020-07-01 00:03:00,105552,2020-07-01 00:03:00,20.06,-24.383652,66.025922,203.808965,0.790212,0.365214,Gibbous,48.0,41.0,0.0,26.0,41.0,SCT,2020-06-30
2020-07-01 00:04:00,105553,2020-07-01 00:04:00,20.10,-24.433650,66.260266,203.563843,0.790278,0.365214,Gibbous,48.0,41.0,0.0,26.0,41.0,SCT,2020-06-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-07-31 23:55:00,122227,2020-07-31 23:55:00,19.31,-28.826771,40.131685,229.317891,0.922016,0.426347,Gibbous,792.0,37.0,0.0,37.0,24.0,SCT,2020-07-31
2020-07-31 23:56:00,122228,2020-07-31 23:56:00,19.32,-28.889598,40.349421,229.074545,0.922056,0.426347,Gibbous,792.0,37.0,0.0,37.0,24.0,SCT,2020-07-31
2020-07-31 23:57:00,122229,2020-07-31 23:57:00,19.32,-28.951610,40.567065,228.831172,0.922096,0.426347,Gibbous,792.0,37.0,0.0,37.0,24.0,SCT,2020-07-31
2020-07-31 23:58:00,122230,2020-07-31 23:58:00,19.33,-29.012802,40.784617,228.587785,0.922136,0.426347,Gibbous,792.0,37.0,0.0,37.0,24.0,SCT,2020-07-31
2020-07-31 23:59:00,122231,2020-07-31 23:59:00,19.33,-29.073173,41.002073,228.344384,0.922176,0.426347,Gibbous,792.0,37.0,0.0,37.0,24.0,SCT,2020-07-31

In [213]:
# Define filtering conditions
phases = ['Full', 'Gibbous', 'Crescent', 'Quarter']
alts = [-5, -5, -5, -5]

# Remove data that meets these lunar phase conditions:
for phase, alt in zip(phases, alts):
    df_mo.loc[(df_mo['lunarphaseclass'] == phase) & (df_mo['lunar_alt'] >= alt), 'mags'] = float('nan')

# Filter out cloud coverage
coverages = ['OVC', 'SCT', 'FEW', 'BKN', 'M']
for cover in coverages:
    df_mo.loc[df_mo['CC'] == cover, 'mags'] = float('nan')

In [ ]:

hours = df_mo.index.hour + df_mo.index.minute / 60
hours = np.where(hours < 20, hours + 24, hours)  # Adjust hours to be in the range of 20-30 for 8pm-6am
df_mo['adjusted_hours'] = hours

print(f'{df_mo.index.min()} to {df_mo.index.max()}')

print(df_mo['adjusted_hours'].min(), df_mo['adjusted_hours'].max())

2020-07-01 00:00:00 to 2020-07-31 23:59:00
20.0 43.983333333333334
2020-07-09 01:31:00 to 2020-07-22 03:50:00

/var/folders/hx/hcs55bp10f5fdvcmjf0rmf4r0000gn/T/ipykernel_70673/1060563578.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Unnamed: 0.1,date,mags,sunalt_deg,lunar_alt,lunar_az,lunar_fraction,lunar_phase,lunarphaseclass,Unnamed: 0,cloudcover,cloudcover_low,cloudcover_mid,cloudcover_high,CC,night,adjusted_hours
date,,,,,,,,,,,,,,,,,
2020-07-09 01:31:00,109839,2020-07-09 01:31:00,19.77,-26.453097,-15.439928,288.172375,0.843462,0.645870,Gibbous,242.0,4.0,0.0,4.0,0.0,CLR,2020-07-08,25.516667
2020-07-09 01:32:00,109840,2020-07-09 01:32:00,19.76,-26.431150,-15.212161,287.931269,0.843411,0.645870,Gibbous,242.0,4.0,0.0,4.0,0.0,CLR,2020-07-08,25.533333
2020-07-09 01:33:00,109841,2020-07-09 01:33:00,19.74,-26.408363,-14.984311,287.690191,0.843361,0.645870,Gibbous,242.0,4.0,0.0,4.0,0.0,CLR,2020-07-08,25.550000
2020-07-09 01:34:00,109842,2020-07-09 01:34:00,19.73,-26.384735,-14.756378,287.449058,0.843310,0.645870,Gibbous,242.0,4.0,0.0,4.0,0.0,CLR,2020-07-08,25.566667
2020-07-09 01:35:00,109843,2020-07-09 01:35:00,19.71,-26.360267,-14.528360,287.207925,0.843260,0.645870,Gibbous,242.0,4.0,0.0,4.0,0.0,CLR,2020-07-08,25.583333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-07-22 03:46:00,116971,2020-07-22 03:46:00,18.70,-18.571138,-45.481014,44.403333,0.027297,0.067885,New,556.0,1.0,0.0,1.0,0.0,CLR,2020-07-21,27.766667
2020-07-22 03:47:00,116972,2020-07-22 03:47:00,18.57,-18.451176,-45.703681,44.165700,0.027322,0.067885,New,556.0,1.0,0.0,1.0,0.0,CLR,2020-07-21,27.783333
2020-07-22 03:48:00,116973,2020-07-22 03:48:00,18.43,-18.330671,-45.926288,43.928085,0.027348,0.067885,New,556.0,1.0,0.0,1.0,0.0,CLR,2020-07-21,27.800000
2020-07-22 03:49:00,116974,2020-07-22 03:49:00,18.30,-18.209627,-46.148825,43.690480,0.027374,0.067885,New,556.0,1.0,0.0,1.0,0.0,CLR,2020-07-21,27.816667
2020-07-22 03:50:00,116975,2020-07-22 03:50:00,18.16,-18.088047,-46.371295,43.452885,0.027400,0.067885,New,556.0,1.0,0.0,1.0,0.0,CLR,2020-07-21,27.833333

## ERROR IS HAPPENING HERE <br>
TOO MANY DATES BEING REMOVED

In [ ]:

# Filter only nighttime hours (8pm-6am)
t_start = 20 # 8pm
t_end = 6 #  6am
# df_night = df_mo[((hours >= t_start) | (hours < t_end)) & df_mo['mags'].notna()].copy()
df_night = df_mo[(hours >= t_start) & (hours <= t_end + 24) & df_mo['mags'].notna()].copy()
print(f'{df_night.index.min()} to {df_night.index.max()}')

df_night

### Sort valid dates and assign colors

In [215]:

# Filter to a date range 
#   – Check sqm2020_interactive for reasonable data date ranges!
# df_night = df_night[(df_night['night'] >= t_start) & (df_night['night'] <= t_end)]

# Convert 'mags' to candela per square meter
df_night['candela'] = 108000*10**(-0.4*df_night['mags'])

# Get the Timestamp of nights
print(f"First night: {df_night['night'].min()}")
print(f"Last night: {df_night['night'].max()}")
print(f"Number of nights: {len(df_night['night'].unique())}")
nights = sorted(df_night['night'].unique()) # list of sorted nights (Timestamps)

# Assign colors for each night
cmap = cm.brg
colors = cmap(np.linspace(0, 1, len(nights)))
night_color = {night: color for night, color in zip(nights, colors)}

print(f"Number of nights: {len(nights)}")

First night: 2020-07-08 00:00:00
Last night: 2020-07-21 00:00:00
Number of nights: 10
Number of nights: 10

### Plot the data

In [217]:
from numpy.polynomial import polynomial as P

plot_bestfit = False
plot_scatter = True

fig = go.Figure()

for night, group in df_night.groupby('night'):
    
    # Use fractional hours for x-axis, wrapping past-midnight ti000mes
    # hours = group.index.hour + group.index.minute / 60
    # hours = np.where(hours < t_start, hours + 24, hours)  # 1am -> 25, etc

    night_str = night.strftime('%Y-%m-%d')

    print(group)

    if plot_scatter:
        fig.add_trace(
            go.Scatter(
                x=group['adjusted_hours'], 
                y=group['candela'], 
                name=night_str, 
                mode='markers',
                marker=dict(
                    size=8,
                ),
                ))
    
    # Add a best-fit line with variance:
    if plot_bestfit:
        if len(hours) < 6:
            continue

        # Sort by hour for a clean line
        sort_idx = np.argsort(hours)
        hours_sorted = hours[sort_idx]
        mags_sorted = group['candela'][sort_idx]

        # Fit 5th degree polynomial
        coeffs = np.polyfit(hours_sorted, mags_sorted, 4)
        poly = np.poly1d(coeffs)

        # Evaluate on a smooth grid
        x_grid = np.linspace(hours_sorted.min(), hours_sorted.max(), 300)
        y_fit = poly(x_grid)

        # Residual std dev as variance estimate
        y_at_data = poly(hours_sorted)
        residuals = mags_sorted - y_at_data
        std = np.std(residuals)

        color = night_color[night]
        ax.plot(x_grid, y_fit, color=color, linewidth=1.5, label=str(night.date()))
        ax.fill_between(x_grid, y_fit - std, y_fit + std, color=color, alpha=0.15)

fig.update_layout(
    title=dict(
        text=f'SQM Measurements: {loc}, {year}'
    ),
    xaxis=dict(
        title=dict(text='Hour'),
        tickmode='array',
        tickvals=[20,21, 22, 23, 24, 25,26,27,28,29,30],
        ticktext=['8pm','9pm','10pm','11pm','12am','1am','2am','3am','4am','5am','6am']
    ),
    yaxis=dict(
        title=dict(text='Cd/m^2')
    ),
)

fig.show()
fig.write_html(f'./{loc}_{t_start}_{t_end}_interactive.html')

                     Unnamed: 0.1                 date   mags  sunalt_deg  \
date
2020-07-09 01:31:00        109839  2020-07-09 01:31:00  19.77  -26.453097
2020-07-09 01:32:00        109840  2020-07-09 01:32:00  19.76  -26.431150
2020-07-09 01:33:00        109841  2020-07-09 01:33:00  19.74  -26.408363
2020-07-09 01:34:00        109842  2020-07-09 01:34:00  19.73  -26.384735
2020-07-09 01:35:00        109843  2020-07-09 01:35:00  19.71  -26.360267
2020-07-09 01:36:00        109844  2020-07-09 01:36:00  19.70  -26.334961
2020-07-09 01:37:00        109845  2020-07-09 01:37:00  19.68  -26.308817
2020-07-09 01:38:00        109846  2020-07-09 01:38:00  19.66  -26.281837
2020-07-09 01:39:00        109847  2020-07-09 01:39:00  19.65  -26.254021
2020-07-09 01:40:00        109848  2020-07-09 01:40:00  19.63  -26.225372
2020-07-09 01:41:00        109849  2020-07-09 01:41:00  19.60  -26.195889
2020-07-09 01:42:00        109850  2020-07-09 01:42:00  19.60  -26.165574
2020-07-09 01:43:00        109851  2020-07-09 01:43:00  19.59  -26.134429
2020-07-09 01:44:00        109852  2020-07-09 01:44:00  19.57  -26.102454
2020-07-09 01:45:00        109853  2020-07-09 01:45:00  19.56  -26.069651
2020-07-09 01:46:00        109854  2020-07-09 01:46:00  19.55  -26.036021
2020-07-09 01:47:00        109855  2020-07-09 01:47:00  19.55  -26.001565
2020-07-09 01:48:00        109856  2020-07-09 01:48:00  19.54  -25.966286
2020-07-09 01:49:00        109857  2020-07-09 01:49:00  19.53  -25.930183
2020-07-09 01:50:00        109858  2020-07-09 01:50:00  19.53  -25.893260
2020-07-09 01:51:00        109859  2020-07-09 01:51:00  19.52  -25.855516
2020-07-09 01:52:00        109860  2020-07-09 01:52:00  19.51  -25.816954
2020-07-09 01:53:00        109861  2020-07-09 01:53:00  19.51  -25.777575
2020-07-09 01:54:00        109862  2020-07-09 01:54:00  19.50  -25.737381
2020-07-09 01:55:00        109863  2020-07-09 01:55:00  19.50  -25.696373
2020-07-09 01:56:00        109864  2020-07-09 01:56:00  19.50  -25.654553
2020-07-09 01:57:00        109865  2020-07-09 01:57:00  19.49  -25.611922
2020-07-09 01:58:00        109866  2020-07-09 01:58:00  19.49  -25.568482
2020-07-09 01:59:00        109867  2020-07-09 01:59:00  19.49  -25.524235
2020-07-09 02:00:00        109868  2020-07-09 02:00:00  19.50  -25.479183
2020-07-09 02:01:00        109869  2020-07-09 02:01:00  19.48  -25.433327
2020-07-09 02:02:00        109870  2020-07-09 02:02:00  19.48  -25.386669
2020-07-09 02:03:00        109871  2020-07-09 02:03:00  19.48  -25.339210
2020-07-09 02:04:00        109872  2020-07-09 02:04:00  19.47  -25.290953
2020-07-09 02:05:00        109873  2020-07-09 02:05:00  19.46  -25.241900
2020-07-09 02:06:00        109874  2020-07-09 02:06:00  19.46  -25.192051
2020-07-09 02:07:00        109875  2020-07-09 02:07:00  19.45  -25.141410
2020-07-09 02:08:00        109876  2020-07-09 02:08:00  19.44  -25.089978
2020-07-09 02:09:00        109877  2020-07-09 02:09:00  19.44  -25.037757
2020-07-09 02:10:00        109878  2020-07-09 02:10:00  19.44  -24.984748
2020-07-09 02:11:00        109879  2020-07-09 02:11:00  19.44  -24.930955
2020-07-09 02:12:00        109880  2020-07-09 02:12:00  19.43  -24.876378
2020-07-09 02:13:00        109881  2020-07-09 02:13:00  19.43  -24.821020
2020-07-09 02:14:00        109882  2020-07-09 02:14:00  19.43  -24.764884

                     lunar_alt    lunar_az  lunar_fraction  lunar_phase  \
date
2020-07-09 01:31:00 -15.439928  288.172375        0.843462     0.645870
2020-07-09 01:32:00 -15.212161  287.931269        0.843411     0.645870
2020-07-09 01:33:00 -14.984311  287.690191        0.843361     0.645870
2020-07-09 01:34:00 -14.756378  287.449058        0.843310     0.645870
2020-07-09 01:35:00 -14.528360  287.207925        0.843260     0.645870
2020-07-09 01:36:00 -14.300263  286.966792        0.843210     0.645870
2020-07-09 01:37:00 -14.072083  286.725631        0.843159     0.645870
2020-07-09 01:38:00 -13.843822  286.484444        0.843109     0.645870
2020-07-09 01:39:00 -13.615481  286.243256        0.843059     0.645870
2020-07-09 01:40:00 -13.387061  286.002041        0.843008     0.645870
2020-07-09 01:41:00 -13.158560  285.760799        0.842958     0.645870
2020-07-09 01:42:00 -12.929982  285.519557        0.842907     0.645870
2020-07-09 01:43:00 -12.701325  285.278287        0.842857     0.645870
2020-07-09 01:44:00 -12.472591  285.037017        0.842807     0.645870
2020-07-09 01:45:00 -12.243780  284.795720        0.842756     0.645870
2020-07-09 01:46:00 -12.014893  284.554396        0.842706     0.645870
2020-07-09 01:47:00 -11.785929  284.313072        0.842655     0.645870
2020-07-09 01:48:00 -11.556891  284.071720        0.842605     0.645870
2020-07-09 01:49:00 -11.327777  283.830369        0.842554     0.645870
2020-07-09 01:50:00 -11.098590  283.588990        0.842504     0.645870
2020-07-09 01:51:00 -10.869328  283.347584        0.842453     0.645870
2020-07-09 01:52:00 -10.639994  283.106177        0.842403     0.645870
2020-07-09 01:53:00 -10.410586  282.864744        0.842353     0.645870
2020-07-09 01:54:00 -10.181106  282.623310        0.842302     0.645870
2020-07-09 01:55:00  -9.951556  282.381850        0.842252     0.648648
2020-07-09 01:56:00  -9.721932  282.140361        0.842201     0.648648
2020-07-09 01:57:00  -9.492239  281.898873        0.842151     0.648648
2020-07-09 01:58:00  -9.262476  281.657358        0.842100     0.648648
2020-07-09 01:59:00  -9.032643  281.415842        0.842050     0.648648
2020-07-09 02:00:00  -8.802739  281.174299        0.841999     0.648648
2020-07-09 02:01:00  -8.572768  280.932729        0.841949     0.648648
2020-07-09 02:02:00  -8.342728  280.691159        0.841898     0.648648
2020-07-09 02:03:00  -8.110117  280.449562        0.841847     0.648648
2020-07-09 02:04:00  -7.872619  280.207937        0.841797     0.648648
2020-07-09 02:05:00  -7.633649  279.966312        0.841746     0.648648
2020-07-09 02:06:00  -7.392885  279.724660        0.841696     0.648648
2020-07-09 02:07:00  -7.149901  279.483008        0.841645     0.648648
2020-07-09 02:08:00  -6.904139  279.241329        0.841595     0.648648
2020-07-09 02:09:00  -6.654790  278.999622        0.841544     0.648648
2020-07-09 02:10:00  -6.400851  278.757915        0.841494     0.648648
2020-07-09 02:11:00  -6.140775  278.516181        0.841443     0.648648
2020-07-09 02:12:00  -5.872285  278.274447        0.841392     0.648648
2020-07-09 02:13:00  -5.591799  278.032658        0.841342     0.648648
2020-07-09 02:14:00  -5.293192  277.790897        0.841291     0.648648

                    lunarphaseclass  Unnamed: 0  cloudcover  cloudcover_low  \
date
2020-07-09 01:31:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:32:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:33:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:34:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:35:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:36:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:37:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:38:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:39:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:40:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:41:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:42:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:43:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:44:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:45:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:46:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:47:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:48:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:49:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:50:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:51:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:52:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:53:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:54:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:55:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:56:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:57:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:58:00         Gibbous       242.0         4.0             0.0
2020-07-09 01:59:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:00:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:01:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:02:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:03:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:04:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:05:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:06:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:07:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:08:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:09:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:10:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:11:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:12:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:13:00         Gibbous       242.0         4.0             0.0
2020-07-09 02:14:00         Gibbous       242.0         4.0             0.0

                     cloudcover_mid  cloudcover_high   CC      night  \
date
2020-07-09 01:31:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:32:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:33:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:34:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:35:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:36:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:37:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:38:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:39:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:40:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:41:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:42:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:43:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:44:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:45:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:46:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:47:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:48:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:49:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:50:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:51:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:52:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:53:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:54:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:55:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:56:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:57:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:58:00             4.0              0.0  CLR 2020-07-08
2020-07-09 01:59:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:00:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:01:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:02:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:03:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:04:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:05:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:06:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:07:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:08:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:09:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:10:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:11:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:12:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:13:00             4.0              0.0  CLR 2020-07-08
2020-07-09 02:14:00             4.0              0.0  CLR 2020-07-08

                     adjusted_hours   candela
date
2020-07-09 01:31:00       25.516667  0.001335
2020-07-09 01:32:00       25.533333  0.001347
2020-07-09 01:33:00       25.550000  0.001372
2020-07-09 01:34:00       25.566667  0.001385
2020-07-09 01:35:00       25.583333  0.001411
2020-07-09 01:36:00       25.600000  0.001424
2020-07-09 01:37:00       25.616667  0.001450
2020-07-09 01:38:00       25.633333  0.001477
2020-07-09 01:39:00       25.650000  0.001491
2020-07-09 01:40:00       25.666667  0.001519
2020-07-09 01:41:00       25.683333  0.001561
2020-07-09 01:42:00       25.700000  0.001561
2020-07-09 01:43:00       25.716667  0.001576
2020-07-09 01:44:00       25.733333  0.001605
2020-07-09 01:45:00       25.750000  0.001620
2020-07-09 01:46:00       25.766667  0.001635
2020-07-09 01:47:00       25.783333  0.001635
2020-07-09 01:48:00       25.800000  0.001650
2020-07-09 01:49:00       25.816667  0.001665
2020-07-09 01:50:00       25.833333  0.001665
2020-07-09 01:51:00       25.850000  0.001680
2020-07-09 01:52:00       25.866667  0.001696
2020-07-09 01:53:00       25.883333  0.001696
2020-07-09 01:54:00       25.900000  0.001712
2020-07-09 01:55:00       25.916667  0.001712
2020-07-09 01:56:00       25.933333  0.001712
2020-07-09 01:57:00       25.950000  0.001728
2020-07-09 01:58:00       25.966667  0.001728
2020-07-09 01:59:00       25.983333  0.001728
2020-07-09 02:00:00       26.000000  0.001712
2020-07-09 02:01:00       26.016667  0.001744
2020-07-09 02:02:00       26.033333  0.001744
2020-07-09 02:03:00       26.050000  0.001744
2020-07-09 02:04:00       26.066667  0.001760
2020-07-09 02:05:00       26.083333  0.001776
2020-07-09 02:06:00       26.100000  0.001776
2020-07-09 02:07:00       26.116667  0.001792
2020-07-09 02:08:00       26.133333  0.001809
2020-07-09 02:09:00       26.150000  0.001809
2020-07-09 02:10:00       26.166667  0.001809
2020-07-09 02:11:00       26.183333  0.001809
2020-07-09 02:12:00       26.200000  0.001826
2020-07-09 02:13:00       26.216667  0.001826
2020-07-09 02:14:00       26.233333  0.001826
                     Unnamed: 0.1                 date   mags  sunalt_deg  \
date
2020-07-10 00:31:00        110315  2020-07-10 00:31:00  20.28  -26.336909
2020-07-10 00:32:00        110316  2020-07-10 00:32:00  20.27  -26.366021
2020-07-10 00:33:00        110317  2020-07-10 00:33:00  20.28  -26.394298
2020-07-10 00:34:00        110318  2020-07-10 00:34:00  20.29  -26.421738
2020-07-10 00:35:00        110319  2020-07-10 00:35:00  20.29  -26.448340
...                           ...                  ...    ...         ...
2020-07-10 02:58:00        110454  2020-07-10 02:58:00  18.29  -21.688004
2020-07-10 02:59:00        110455  2020-07-10 02:59:00  18.54  -21.599159
2020-07-10 03:00:00        110456  2020-07-10 03:00:00  18.40  -21.509647
2020-07-10 03:01:00        110457  2020-07-10 03:01:00  18.45  -21.419468
2020-07-10 03:02:00        110458  2020-07-10 03:02:00  18.41  -21.328627

                     lunar_alt    lunar_az  lunar_fraction  lunar_phase  \
date
2020-07-10 00:31:00 -40.169278  313.272582        0.769017     0.676436
2020-07-10 00:32:00 -39.946911  313.032487        0.768959     0.676436
2020-07-10 00:33:00 -39.724380  312.792393        0.768902     0.676436
2020-07-10 00:34:00 -39.501685  312.552270        0.768845     0.676436
2020-07-10 00:35:00 -39.278830  312.312148        0.768788     0.676436
...                        ...         ...             ...          ...
2020-07-10 02:58:00  -6.213243  277.830512        0.760568     0.679215
2020-07-10 02:59:00  -5.941787  277.588259        0.760510     0.679215
2020-07-10 03:00:00  -5.658982  277.346006        0.760452     0.679215
2020-07-10 03:01:00  -5.359156  277.103725        0.760394     0.679215
2020-07-10 03:02:00  -5.031809  276.861417        0.760337     0.679215

                    lunarphaseclass  Unnamed: 0  cloudcover  cloudcover_low  \
date
2020-07-10 00:31:00         Gibbous       265.0         8.0             0.0
2020-07-10 00:32:00         Gibbous       265.0         8.0             0.0
2020-07-10 00:33:00         Gibbous       265.0         8.0             0.0
2020-07-10 00:34:00         Gibbous       265.0         8.0             0.0
2020-07-10 00:35:00         Gibbous       265.0         8.0             0.0
...                             ...         ...         ...             ...
2020-07-10 02:58:00         Gibbous       267.0         1.0             0.0
2020-07-10 02:59:00         Gibbous       267.0         1.0             0.0
2020-07-10 03:00:00         Gibbous       267.0         1.0             0.0
2020-07-10 03:01:00         Gibbous       267.0         1.0             0.0
2020-07-10 03:02:00         Gibbous       267.0         1.0             0.0

                     cloudcover_mid  cloudcover_high   CC      night  \
date
2020-07-10 00:31:00             8.0              0.0  CLR 2020-07-09
2020-07-10 00:32:00             8.0              0.0  CLR 2020-07-09
2020-07-10 00:33:00             8.0              0.0  CLR 2020-07-09
2020-07-10 00:34:00             8.0              0.0  CLR 2020-07-09
2020-07-10 00:35:00             8.0              0.0  CLR 2020-07-09
...                             ...              ...  ...        ...
2020-07-10 02:58:00             1.0              0.0  CLR 2020-07-09
2020-07-10 02:59:00             1.0              0.0  CLR 2020-07-09
2020-07-10 03:00:00             1.0              0.0  CLR 2020-07-09
2020-07-10 03:01:00             1.0              0.0  CLR 2020-07-09
2020-07-10 03:02:00             1.0              0.0  CLR 2020-07-09

                     adjusted_hours   candela
date
2020-07-10 00:31:00       24.516667  0.000834
2020-07-10 00:32:00       24.533333  0.000842
2020-07-10 00:33:00       24.550000  0.000834
2020-07-10 00:34:00       24.566667  0.000827
2020-07-10 00:35:00       24.583333  0.000827
...                             ...       ...
2020-07-10 02:58:00       26.966667  0.005217
2020-07-10 02:59:00       26.983333  0.004144
2020-07-10 03:00:00       27.000000  0.004714
2020-07-10 03:01:00       27.016667  0.004502
2020-07-10 03:02:00       27.033333  0.004671

[144 rows x 18 columns]
                     Unnamed: 0.1                 date   mags  sunalt_deg  \
date
2020-07-11 03:31:00        111021  2020-07-11 03:31:00  18.65  -18.550704
2020-07-11 03:32:00        111022  2020-07-11 03:32:00  18.57  -18.441152
2020-07-11 03:33:00        111023  2020-07-11 03:33:00  18.48  -18.331022
2020-07-11 03:34:00        111024  2020-07-11 03:34:00  18.38  -18.220316
2020-07-11 03:35:00        111025  2020-07-11 03:35:00  18.29  -18.109037

                     lunar_alt    lunar_az  lunar_fraction  lunar_phase  \
date
2020-07-11 03:31:00  -9.194234  280.000600        0.671703      0.71256
2020-07-11 03:32:00  -8.955943  279.758210        0.671640      0.71256